#! /bin/bash
if test $(echo $2 | wc -c) != 1
then
	BASE=$2
else
	BASE=0123456789
fi
if test $(echo $3 | wc -c) == 8
then
	OPER=$3
else
	OPER='()+-*/%'
fi
LEN=$(($(echo $1 | wc -c)-1))
echo "$1" | ./calc $BASE $OPER $LEN
